### ISSUE TITLE
Why not use the author info during the ACR?

### ISSUE THREAD

**Issue by zippeurfou** [gabrielspmoreira/chameleon_recsys#1]
Hi,
I have read the paper and I am wondering why the author was only considered during the NER part and not the ACR part. The [paper](https://arxiv.org/pdf/1904.10367.pdf) doesn't really explain why this could not be considered as a metadata attribute or at least i am missing it.
Best,

**Comment by gabrielspmoreira** [comment]
Hi,
In the ACR module, the Article Content Embeddings are trained in a side task: classify articles' categorical metadata, such as Category or Tags, based on the article title and text. You could also use the Author as another target categorical attribute for training. Therefore, I am afraid that content embeddings trained to predict who is the article author might not lead to good content representations for recommendation, compared to categories, which are defined by Editors and are in general very related to the article content. 
Is that clearer?

**Comment by zippeurfou** [comment]
Thanks @gabrielspmoreira for you answer.
I was more thinking of using it as a metadata input feature for ACR training.
For example [you do not use it](https://github.com/gabrielspmoreira/chameleon_recsys/blob/master/acr_module/acr/acr_trainer_adressa.py#L132) for the addressa ACR training but [it get passed to the NAR](https://github.com/gabrielspmoreira/chameleon_recsys/blob/master/acr_module/acr/acr_trainer_adressa.py#L169). On the other hand [it seems to be used](https://github.com/gabrielspmoreira/chameleon_recsys/blob/master/acr_module/acr/acr_trainer_gcom.py#L113) for the gcom ACR training. I was wondering why it was like that?
