### ISSUE TITLE
Flag Mismatch for NAR Trainer

### ISSUE THREAD

**Issue by Curlykonda** [gabrielspmoreira/chameleon_recsys#10]
Hi, 

In the runfile ``run_nar_train_gcom_local.sh``, there seems to be a Flag mismatch. 

In the code, only one path is required that should enable loading labels, metadata and embeddings for the ACR: 
```python
        tf.logging.info('Loading ACR module assets')
        acr_label_encoders, articles_metadata_df, content_article_embeddings_matrix = \
                load_acr_module_resources(FLAGS.acr_module_resources_path)
```

In the runfile, however, there are two Flags, for ACR metadata and embeddings, which are unused in the code.

Perhaps the runfile should be adjusted to execute the code properly (e.g. setting ``acr_module_resources_path``), or alternatively, the code must be adjusted two handle the two Flags separately.

**Comment by whonor** [comment]
Hi there,
I also have the same problem, as following:

![ERROR](https://user-images.githubusercontent.com/24491528/75212121-e6753600-57c0-11ea-9cec-5683c19456c3.png)

I have never edited the resources, is there wrong in resources? 
Could anyone answer the question?
Thanks!

**Comment by CatcherGG** [comment]
It's not only a flag-mismatch: https://github.com/gabrielspmoreira/chameleon_recsys/issues/9.
There's missing data: **nar_label_encoders**.

**Comment by gabrielspmoreira** [comment]
Hi. Sorry for the delayed response. The `nar_trainer_gcom.py` in fact had an issue, requiring some assets that were not available for the G1 dataset (as the raw textual content of the articles could not be released for that dataset). Now, the information required from the ACR module for the NAR training are only the following command line parameters (`--acr_module_articles_metadata_csv_path` and `--acr_module_articles_content_embeddings_pickle_path`), which correspond to the files available in the [public dataset URL](https://www.kaggle.com/gspmoreira/news-portal-user-interactions-by-globocom?select=articles_metadata.csv).
