### ISSUE TITLE
Get predictions on input data

### ISSUE THREAD

**Issue by 13520505** [gabrielspmoreira/chameleon_recsys#2]
Hi,
When using NAR module, I want to see a rank list for predictions in other to have intuitive evaluation on recommendations articles after training process. But I only see the evaluation code to calculate metrics. Can you help me to get this ranking list?

Thank you very much.

**Comment by gabrielspmoreira** [comment]
Hi. Sorry for the late response. If you enable the hyperparameter `--save_eval_sessions_recommendations` at on of the NAR trainer script (e.g. nar_trainer_gcom.py), a file named 'eval_chameleon_recommendations_log.json' will be output with the labels (next-clicks) and the ranked items. Take a look in the `save_sessions_chameleon_recommendations_log()` method

**Comment by gabrielspmoreira** [comment]
Hi. Sorry for the late response. If you enable the hyperparameter --save_eval_sessions_recommendations at on of the NAR trainer script (e.g. nar_trainer_gcom.py), a file named 'eval_chameleon_recommendations_log.json' will be output with the labels (next-clicks) and the ranked items. Take a look in the save_sessions_chameleon_recommendations_log() method
