### ISSUE TITLE
Requirements & Dependencies

### ISSUE THREAD

**Issue by Curlykonda** [gabrielspmoreira/chameleon_recsys#8]
Hello, 
In order to run the code and reproduce results, one would need the specific package versions you used for the development and experiments. 

Could you provide `requirements.txt` or some other specification of the packages and version?

In the README the dependencies appear to be underspecified. Especially with regards to the Tensorflow version 1.12.0, the required packages are crucial. 

Thank you in advance.

**Comment by CatcherGG** [comment]
Upvote. Requirements are crucial.

**Comment by gabrielspmoreira** [comment]
Sorry about that. Now `requirements.txt` is included
